// Reads the JSON snapshot under /data (generated by
// `backend/app/export_static.py`) instead of calling a live backend — this is
// what powers the GitHub Pages build (VITE_STATIC=true). Same method names
// and signatures as liveClient.ts, so client.ts can swap them in for free and
// every hook / page / component is unaware which one is active.
import type {
  Competition,
  Match,
  MatchDetail,
  ScorersResponse,
  SearchResults,
  Standings,
  Team,
  TeamDetail,
} from './types'

const DATA_BASE = `${import.meta.env.BASE_URL}data`.replace(/\/+$/, '')

const cache = new Map<string, Promise<unknown>>()

function getJson<T>(path: string): Promise<T> {
  let p = cache.get(path) as Promise<T> | undefined
  if (!p) {
    p = fetch(`${DATA_BASE}/${path}`).then((res) => {
      if (!res.ok) {
        throw new Error(
          res.status === 404
            ? `Not in this static snapshot: ${path}`
            : `${res.status} loading ${path}`,
        )
      }
      return res.json() as Promise<T>
    })
    cache.set(path, p)
  }
  return p
}

async function latestSeason(code: string): Promise<string | undefined> {
  const seasons = await getJson<string[]>(`competitions/${code}/seasons.json`)
  return seasons[0]
}

interface SearchIndex {
  competitions: Competition[]
  teams: Team[]
}

function todayUtc(): string {
  return new Date().toISOString().slice(0, 10)
}

export const staticApi = {
  competitions: () => getJson<Competition[]>('competitions.json'),

  competition: (code: string) => getJson<Competition>(`competitions/${code}/index.json`),

  seasons: (code: string) => getJson<string[]>(`competitions/${code}/seasons.json`),

  standings: async (code: string, season?: string): Promise<Standings> => {
    const s = season ?? (await latestSeason(code))
    if (!s) return { competition: await staticApi.competition(code), season: null, groups: [] }
    return getJson<Standings>(`competitions/${code}/standings/${s}.json`)
  },

  competitionMatches: async (
    code: string,
    params?: { matchday?: number; status?: string; season?: string },
  ): Promise<Match[]> => {
    const s = params?.season ?? (await latestSeason(code))
    if (!s) return []
    let matches = await getJson<Match[]>(`competitions/${code}/matches/${s}.json`)
    if (params?.matchday != null) matches = matches.filter((m) => m.matchday === params.matchday)
    if (params?.status) matches = matches.filter((m) => m.status === params.status?.toUpperCase())
    return matches
  },

  scorers: async (code: string, season?: string, limit = 20): Promise<ScorersResponse> => {
    const s = season ?? (await latestSeason(code))
    if (!s) return { competition: await staticApi.competition(code), season: null, scorers: [] }
    const data = await getJson<ScorersResponse>(`competitions/${code}/scorers/${s}.json`)
    return { ...data, scorers: data.scorers.slice(0, limit) }
  },

  matchesOn: async (date?: string): Promise<Match[]> => {
    const day = date ?? todayUtc()
    const all = await getJson<Match[]>('matches/window.json')
    return all.filter((m) => m.utc_date.slice(0, 10) === day)
  },

  match: (id: number | string) => getJson<MatchDetail>(`matches/${id}.json`),

  team: (id: number | string) => getJson<TeamDetail>(`teams/${id}.json`),

  search: async (q: string): Promise<SearchResults> => {
    const index = await getJson<SearchIndex>('search-index.json')
    const needle = q.trim().toLowerCase()
    if (!needle) return { teams: [], competitions: [] }
    const teams = index.teams
      .filter(
        (t) =>
          t.name.toLowerCase().includes(needle) ||
          t.short_name?.toLowerCase().includes(needle) ||
          t.tla?.toLowerCase() === needle,
      )
      .sort((a, b) => a.name.length - b.name.length)
      .slice(0, 8)
    const competitions = index.competitions
      .filter((c) => c.name.toLowerCase().includes(needle) || c.code.toLowerCase() === needle)
      .slice(0, 5)
    return { teams, competitions }
  },
}
