"""uefa team refs, penalty scores, uefa_synced_at

Revision ID: edd22f0eaccb
Revises: 6f1b13f1efb7
Create Date: 2026-09-21 18:50:08.509615
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'edd22f0eaccb'
down_revision: str | None = '6f1b13f1efb7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_external_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_team_external_ref'),
    sa.UniqueConstraint('team_id', 'provider', name='uq_team_external_ref_team')
    )
    with op.batch_alter_table('team_external_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_external_refs_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_external_refs_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_score_pen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_score_pen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uefa_synced_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('uefa_synced_at')
        batch_op.drop_column('away_score_pen')
        batch_op.drop_column('home_score_pen')

    with op.batch_alter_table('team_external_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_external_refs_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_external_refs_external_id'))

    op.drop_table('team_external_refs')
    # ### end Alembic commands ###
