"""initial schema

Revision ID: 42fb3f27a331
Revises: 
Create Date: 2026-09-08 12:36:16.911958
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '42fb3f27a331'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('emblem_url', sa.String(length=300), nullable=True),
    sa.Column('area_name', sa.String(length=80), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('area_flag', sa.String(length=300), nullable=True),
    sa.Column('current_season', sa.String(length=10), nullable=True),
    sa.Column('current_season_start', sa.Date(), nullable=True),
    sa.Column('current_season_end', sa.Date(), nullable=True),
    sa.Column('current_matchday', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_competitions_provider_id'), ['provider_id'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=80), nullable=True),
    sa.Column('tla', sa.String(length=10), nullable=True),
    sa.Column('crest_url', sa.String(length=300), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('club_colors', sa.String(length=120), nullable=True),
    sa.Column('venue', sa.String(length=160), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('coach_name', sa.String(length=120), nullable=True),
    sa.Column('area_name', sa.String(length=80), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_provider_id'), ['provider_id'], unique=True)

    op.create_table('competition_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'team_id', 'season', name='uq_competition_team_season')
    )
    with op.batch_alter_table('competition_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_teams_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competition_teams_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_competition_teams_team_id'), ['team_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('group', sa.String(length=40), nullable=True),
    sa.Column('utc_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_score_ht', sa.Integer(), nullable=True),
    sa.Column('away_score_ht', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=12), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('venue', sa.String(length=160), nullable=True),
    sa.Column('referees', sa.JSON(), nullable=True),
    sa.Column('provider_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_matchday'), ['matchday'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_provider_id'), ['provider_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_matches_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_utc_date'), ['utc_date'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_provider_id'), ['provider_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('scorers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('player_provider_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('played_matches', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'season', 'player_name', 'team_id', name='uq_scorer_row')
    )
    with op.batch_alter_table('scorers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scorers_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scorers_season'), ['season'], unique=False)

    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('group_name', sa.String(length=40), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('draw', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'season', 'type', 'group_name', 'team_id', name='uq_standing_row')
    )
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standings_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standings_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_standings_team_id'), ['team_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=True),
    sa.Column('card', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_match_id'), ['match_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('injury_time', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('scorer_name', sa.String(length=120), nullable=True),
    sa.Column('scorer_provider_id', sa.Integer(), nullable=True),
    sa.Column('assist_name', sa.String(length=120), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_match_id'), ['match_id'], unique=False)

    op.create_table('substitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('player_in_name', sa.String(length=120), nullable=True),
    sa.Column('player_out_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('substitutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_substitutions_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_substitutions_match_id'))

    op.drop_table('substitutions')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_match_id'))

    op.drop_table('goals')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_match_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standings_team_id'))
        batch_op.drop_index(batch_op.f('ix_standings_season'))
        batch_op.drop_index(batch_op.f('ix_standings_competition_id'))

    op.drop_table('standings')
    with op.batch_alter_table('scorers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scorers_season'))
        batch_op.drop_index(batch_op.f('ix_scorers_competition_id'))

    op.drop_table('scorers')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_provider_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))

    op.drop_table('players')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_utc_date'))
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_season'))
        batch_op.drop_index(batch_op.f('ix_matches_provider_id'))
        batch_op.drop_index(batch_op.f('ix_matches_matchday'))
        batch_op.drop_index(batch_op.f('ix_matches_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_competition_id'))
        batch_op.drop_index(batch_op.f('ix_matches_away_team_id'))

    op.drop_table('matches')
    with op.batch_alter_table('competition_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_teams_team_id'))
        batch_op.drop_index(batch_op.f('ix_competition_teams_season'))
        batch_op.drop_index(batch_op.f('ix_competition_teams_competition_id'))

    op.drop_table('competition_teams')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_provider_id'))

    op.drop_table('teams')
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitions_provider_id'))
        batch_op.drop_index(batch_op.f('ix_competitions_code'))

    op.drop_table('competitions')
    # ### end Alembic commands ###
