"""fpl player match stats and fpl_synced_at

Revision ID: 48437fd5be10
Revises: 442ce291efca
Create Date: 2026-09-09 09:57:42.445282
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '48437fd5be10'
down_revision: str | None = '442ce291efca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_player_ratings', schema=None) as batch_op:
        # server_default backfills any pre-existing rows; new rows set it explicitly.
        batch_op.add_column(
            sa.Column(
                'source', sa.String(length=20), nullable=False,
                server_default='api-football',
            )
        )
        batch_op.add_column(sa.Column('xg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('xa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saves', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_match_player_rating'), type_='unique')
        batch_op.create_unique_constraint('uq_match_player_rating', ['match_id', 'player_name', 'team_id', 'source'])

    with op.batch_alter_table('match_team_stats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_match_team_stat'), type_='unique')
        batch_op.create_unique_constraint('uq_match_team_stat', ['match_id', 'team_id', 'source'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fpl_synced_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('fpl_synced_at')

    with op.batch_alter_table('match_team_stats', schema=None) as batch_op:
        batch_op.drop_constraint('uq_match_team_stat', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_match_team_stat'), ['match_id', 'team_id'])

    with op.batch_alter_table('match_player_ratings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_match_player_rating', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_match_player_rating'), ['match_id', 'player_name', 'team_id'])
        batch_op.drop_column('saves')
        batch_op.drop_column('bonus')
        batch_op.drop_column('bps')
        batch_op.drop_column('xa')
        batch_op.drop_column('xg')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
