"""depth: stats, ratings, external refs

Revision ID: 442ce291efca
Revises: 42fb3f27a331
Create Date: 2026-09-08 12:51:13.950572
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '442ce291efca'
down_revision: str | None = '42fb3f27a331'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_external_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'provider', name='uq_match_external_ref')
    )
    with op.batch_alter_table('match_external_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_external_refs_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_external_refs_match_id'), ['match_id'], unique=False)

    op.create_table('match_player_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('player_provider_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('captain', sa.Boolean(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellow', sa.Integer(), nullable=True),
    sa.Column('red', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_name', 'team_id', name='uq_match_player_rating')
    )
    with op.batch_alter_table('match_player_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_player_ratings_match_id'), ['match_id'], unique=False)

    op.create_table('match_team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('possession', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('passes_accuracy', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_match_team_stat')
    )
    with op.batch_alter_table('match_team_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_team_stats_match_id'), ['match_id'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depth_synced_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('depth_synced_at')

    with op.batch_alter_table('match_team_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_team_stats_match_id'))

    op.drop_table('match_team_stats')
    with op.batch_alter_table('match_player_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_player_ratings_match_id'))

    op.drop_table('match_player_ratings')
    with op.batch_alter_table('match_external_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_external_refs_match_id'))
        batch_op.drop_index(batch_op.f('ix_match_external_refs_external_id'))

    op.drop_table('match_external_refs')
    # ### end Alembic commands ###
