"""fdcouk synced at

Revision ID: 6f1b13f1efb7
Revises: 48437fd5be10
Create Date: 2026-09-16 01:07:23.775802
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6f1b13f1efb7'
down_revision: str | None = '48437fd5be10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fdcouk_synced_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('fdcouk_synced_at')

    # ### end Alembic commands ###
